public class Class_Map1 {
    public static map<integer,string> mp1= new map<integer,string>();
    public void map_method1(){
        mp1.put(1, 'USA');
        mp1.put(2, 'UK');
        mp1.put(3, 'UAE');
        mp1.put(4, 'US');
        mp1.put(5, 'IND');
        mp1.put(6, 'PAK');
        mp1.put(7, 'usa');      
             }
    public void dismap_method1(map<integer,string> mp){
 system.debug(mp);
    }
}