public class Constructor_Leads {

    // First a no-argument constructor
    public Constructor_Leads(){
        system.debug(' First a no-argument constructor');
    }
      // A constructor with one argument
    public Constructor_Leads(integer a){
        system.debug(' A constructor with one argument');

        
    }
      // A constructor with two arguments
    public Constructor_Leads(boolean a ,string s){
                system.debug(' A constructor with two arguments');
    }
}

/*
 Constructor_Leads wc = new Constructor_Leads();
  
Constructor_Leads wc1 = new Constructor_Leads(2);
  
Constructor_Leads wc2 = new Constructor_Leads(false,'');
    
wc2= new Constructor_Leads(true,'');


*/