public class Final_Keyword_Concept {
public final String email;
    public static String sname = 'Raja';
    public Static final String institueName;
    String nm='ll';
    public static void displaySName(String intial){
        Final_Keyword_Concept vc= new Final_Keyword_Concept();
        system.debug('sname value===>'+intial + sname);
                system.debug('institueName value===>'+institueName);
                system.debug('email value===>'+vc.email);

        
    }
}

/*
 Final_Keyword_Concept.institueName ='ARM';
System.debug('Final_Keyword_Concept.sname==>'+Final_Keyword_Concept.sname);
System.debug('Final_Keyword_Concept.institueName==>'+Final_Keyword_Concept.institueName);

StaticFinal_ExampleClassTEST ect1 = new StaticFinal_ExampleClassTEST();
StaticFinal_ExampleClassTEST2 ect2 = new StaticFinal_ExampleClassTEST2();
*/