public class Method_Accepts_Integerparameters {
    public static decimal Two_integerparameters_accepting_method(integer i, integer k){
        decimal result;
        decimal l;
            decimal m;
        l = (i*20)/100;
        m=(k*10)/100;
        result = i+l-m;
         
        system.debug(result);
        return result;        
    }
    
    public static integer Percentage_of_integer_value_method(){
        integer result;
        return result;
        
    }
}