public class  Static_Final_Example_Classs{
    public final string m;
    public static string sname= 'bhupathi';
    public static final string name;
public static void Static_Final_Example_Class_method(string  i){    
    system.debug('sname value=====>'+i+sname);
    //system.debug('Static_Final_Example_Class.sname=====>'+Static_Final_Example_Class.sname);
    //system.debug('Static_Final_Example_Class.name=====>'+Static_Final_Example_Class.name);       
}   
}