public class Two_Strings_to_display {
/*public static void Two_strings_dsp_Method(){
//string string1='HI THIS IS DURGA PRASAD';
//string string2='I AM TAKING COACHING IN SALESFORCE AT ASHWAMEDHA INSTITUTE';
system.debug( '"' +'(' +'string1 is:'+'\'' +string1 + '\'' +',' +'string2 is:' + '\''+string2  +  '\''+ ')'+'"');
 }
*/
    public static void Two_strings_dsp_Method1(){
        List<Integer> li = new List<Integer>{10, 20, 30};
String s = String.join( li, '/');
       
}
}