public class Welcome_Class {
/*public string sname;
public double v1;
    public Boolean v2;
    public integer i;
    public Long l;
    public void assign_method(){
        sname='prasad';
        v1=34444;
        v2=false;
   
           } 
*/
    public void display_method(string sname,double v1, Boolean v2){
        system.debug(sname);
        system.debug(v1);
        system.debug(v2);


        
    }
    }